# Generated by Django 4.1.1 on 2022-09-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.TextField(default='defname', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(verbose_name='Input Text Here'),
        ),
    ]
