# Generated by Django 4.1.1 on 2022-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_text_name_alter_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='content',
        ),
        migrations.AddField(
            model_name='text',
            name='content_eng',
            field=models.TextField(default='defeng', verbose_name='Input English Text Here'),
        ),
        migrations.AddField(
            model_name='text',
            name='content_esp',
            field=models.TextField(default='defesp', verbose_name='Input Spanish Text Here'),
        ),
        migrations.AddField(
            model_name='text',
            name='content_geo',
            field=models.TextField(default='defgeo', verbose_name='Input Georgian Text Here'),
        ),
    ]
