# Generated by Django 4.1.1 on 2022-10-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.TextField(default='defname', verbose_name='Name'),
        ),
    ]
