# Generated by Django 4.1.1 on 2022-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amount_year',
            field=models.IntegerField(default=0, verbose_name='Yearly Price'),
        ),
        migrations.AddField(
            model_name='package',
            name='content1_eng',
            field=models.TextField(default='defeng', verbose_name='Input English Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='content1_esp',
            field=models.TextField(default='defesp', verbose_name='Input Spanish Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='content1_geo',
            field=models.TextField(default='defgeo', verbose_name='Input Georgian Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='content2_eng',
            field=models.TextField(default='defeng', verbose_name='Input English Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='content2_esp',
            field=models.TextField(default='defesp', verbose_name='Input Spanish Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='content2_geo',
            field=models.TextField(default='defgeo', verbose_name='Input Georgian Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='content3_eng',
            field=models.TextField(default='defeng', verbose_name='Input English Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='content3_esp',
            field=models.TextField(default='defesp', verbose_name='Input Spanish Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='content3_geo',
            field=models.TextField(default='defgeo', verbose_name='Input Georgian Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='text_eng',
            field=models.TextField(default='defeng', verbose_name='Input English Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='text_esp',
            field=models.TextField(default='defesp', verbose_name='Input Spanish Text Here'),
        ),
        migrations.AddField(
            model_name='package',
            name='text_geo',
            field=models.TextField(default='defgeo', verbose_name='Input Georgian Text Here'),
        ),
        migrations.AlterField(
            model_name='package',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Monthly Price'),
        ),
    ]
