# Generated by Django 4.1.1 on 2022-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_package_amount_year_package_content1_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='content1_eng',
            field=models.TextField(default='Package Advantage 1 - Eng', verbose_name='Package Advantage 1 - Eng'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content1_esp',
            field=models.TextField(default='Package Advantage 1 - Esp', verbose_name='Package Advantage 1 - Esp'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content1_geo',
            field=models.TextField(default='Package Advantage 1 - Geo', verbose_name='Package Advantage 1 - Geo'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content2_eng',
            field=models.TextField(default='Package Advantage 2 - Eng', verbose_name='Package Advantage 2 - Eng'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content2_esp',
            field=models.TextField(default='Package Advantage 2 - Esp', verbose_name='Package Advantage 2 - Esp'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content2_geo',
            field=models.TextField(default='Package Advantage 2 - Geo', verbose_name='Package Advantage 2 - Geo'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content3_eng',
            field=models.TextField(default='Package Advantage 3 - Eng', verbose_name='Package Advantage 3 - Eng'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content3_esp',
            field=models.TextField(default='Package Advantage 3 - Esp', verbose_name='Package Advantage 3 - Esp'),
        ),
        migrations.AlterField(
            model_name='package',
            name='content3_geo',
            field=models.TextField(default='Package Advantage 3 - Geo', verbose_name='Package Advantage 3 - Geo'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.TextField(default='Name', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='text_eng',
            field=models.TextField(default='Input English Text Here', verbose_name='Input English Text Here'),
        ),
        migrations.AlterField(
            model_name='package',
            name='text_esp',
            field=models.TextField(default='Input Spanish Text Here', verbose_name='Input Spanish Text Here'),
        ),
        migrations.AlterField(
            model_name='package',
            name='text_geo',
            field=models.TextField(default='Input Georgian Text Here', verbose_name='Input Georgian Text Here'),
        ),
    ]
