# Generated by Django 4.1.1 on 2022-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_package_content1_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='defname', verbose_name='Name')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
