# Generated by Django 4.1.1 on 2022-10-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_screenshots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshots',
            new_name='Screenshot',
        ),
    ]
