# Generated by Django 4.1.1 on 2022-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_screenshot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Menu1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Menu Name', verbose_name='Footer Menu Name')),
                ('content_geo', models.TextField(default='defgeo', max_length='15', verbose_name='Input Georgian Text Here')),
                ('content_eng', models.TextField(default='defeng', max_length='15', verbose_name='Input English Text Here')),
                ('content_esp', models.TextField(default='defesp', max_length='15', verbose_name='Input Spanish Text Here')),
            ],
        ),
        migrations.CreateModel(
            name='Footer_Menu2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Menu Name', verbose_name='Footer Menu Name')),
                ('content_geo', models.TextField(default='defgeo', max_length='15', verbose_name='Input Georgian Text Here')),
                ('content_eng', models.TextField(default='defeng', max_length='15', verbose_name='Input English Text Here')),
                ('content_esp', models.TextField(default='defesp', max_length='15', verbose_name='Input Spanish Text Here')),
            ],
        ),
        migrations.CreateModel(
            name='Main_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Menu Name', verbose_name='Menu Name')),
                ('content_geo', models.TextField(default='defgeo', max_length='15', verbose_name='Input Georgian Text Here')),
                ('content_eng', models.TextField(default='defeng', max_length='15', verbose_name='Input English Text Here')),
                ('content_esp', models.TextField(default='defesp', max_length='15', verbose_name='Input Spanish Text Here')),
            ],
        ),
    ]
