# Generated by Django 4.1.1 on 2022-10-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_footer_menu1_footer_menu2_main_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_menu1',
            name='url_eng',
            field=models.TextField(default='https://', verbose_name='Input English URL Here'),
        ),
        migrations.AddField(
            model_name='footer_menu1',
            name='url_esp',
            field=models.TextField(default='https://', verbose_name='Input Spanish URL Here'),
        ),
        migrations.AddField(
            model_name='footer_menu1',
            name='url_geo',
            field=models.TextField(default='https://', verbose_name='Input Georgian URL Here'),
        ),
        migrations.AddField(
            model_name='footer_menu2',
            name='url_eng',
            field=models.TextField(default='https://', verbose_name='Input English URL Here'),
        ),
        migrations.AddField(
            model_name='footer_menu2',
            name='url_esp',
            field=models.TextField(default='https://', verbose_name='Input Spanish URL Here'),
        ),
        migrations.AddField(
            model_name='footer_menu2',
            name='url_geo',
            field=models.TextField(default='https://', verbose_name='Input Georgian URL Here'),
        ),
        migrations.AddField(
            model_name='main_menu',
            name='url_eng',
            field=models.TextField(default='https://', verbose_name='Input English URL Here'),
        ),
        migrations.AddField(
            model_name='main_menu',
            name='url_esp',
            field=models.TextField(default='https://', verbose_name='Input Spanish URL Here'),
        ),
        migrations.AddField(
            model_name='main_menu',
            name='url_geo',
            field=models.TextField(default='https://', verbose_name='Input Georgian URL Here'),
        ),
    ]
