# Generated by Django 4.1.1 on 2022-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_footer_menu1_url_eng_footer_menu1_url_esp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_menu2',
            name='content_eng',
            field=models.TextField(default='defeng', max_length='25', verbose_name='Input English Text Here'),
        ),
        migrations.AlterField(
            model_name='footer_menu2',
            name='content_esp',
            field=models.TextField(default='defesp', max_length='25', verbose_name='Input Spanish Text Here'),
        ),
        migrations.AlterField(
            model_name='footer_menu2',
            name='content_geo',
            field=models.TextField(default='defgeo', max_length='25', verbose_name='Input Georgian Text Here'),
        ),
    ]
