# Generated by Django 4.1.3 on 2022-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_footer_menu2_content_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='defname', verbose_name='Name')),
                ('content_geo', models.TextField(default='defgeo', verbose_name='Input Georgian Text Here')),
                ('content_eng', models.TextField(default='defeng', verbose_name='Input English Text Here')),
                ('content_esp', models.TextField(default='defesp', verbose_name='Input Spanish Text Here')),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='content_eng',
        ),
        migrations.RemoveField(
            model_name='text',
            name='content_esp',
        ),
        migrations.RemoveField(
            model_name='text',
            name='content_geo',
        ),
        migrations.RemoveField(
            model_name='text',
            name='name',
        ),
        migrations.AddField(
            model_name='text',
            name='email',
            field=models.TextField(default='@gmail.com', verbose_name='Input Email Here'),
        ),
        migrations.AddField(
            model_name='text',
            name='first_name',
            field=models.TextField(default='deffname', verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='text',
            name='last_name',
            field=models.TextField(default='deflname', verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='text',
            name='number',
            field=models.TextField(default='+995', verbose_name='Input Number Here'),
        ),
        migrations.AddField(
            model_name='text',
            name='text',
            field=models.TextField(default='deftext', verbose_name='Input Text Here'),
        ),
    ]
