# Generated by Django 4.1.3 on 2022-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_contactform_remove_text_content_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='content_eng',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='content_esp',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='content_geo',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='text',
            name='email',
        ),
        migrations.RemoveField(
            model_name='text',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='text',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='text',
            name='number',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text',
        ),
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.TextField(default='@gmail.com', verbose_name='Input Email Here'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.TextField(default='deffname', verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_name',
            field=models.TextField(default='deflname', verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='number',
            field=models.TextField(default='+995', verbose_name='Input Number Here'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='text',
            field=models.TextField(default='deftext', verbose_name='Input Text Here'),
        ),
        migrations.AddField(
            model_name='text',
            name='content_eng',
            field=models.TextField(default='defeng', verbose_name='Input English Text Here'),
        ),
        migrations.AddField(
            model_name='text',
            name='content_esp',
            field=models.TextField(default='defesp', verbose_name='Input Spanish Text Here'),
        ),
        migrations.AddField(
            model_name='text',
            name='content_geo',
            field=models.TextField(default='defgeo', verbose_name='Input Georgian Text Here'),
        ),
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.TextField(default='defname', verbose_name='Name'),
        ),
    ]
