# Generated by Django 4.1.3 on 2022-11-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_contactform_content_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='@gmail.com', max_length=254, verbose_name='Input Email Here'),
        ),
    ]
