# Generated by Django 4.1.3 on 2023-02-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_category_model3d_product_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='image',
            field=models.ImageField(default='default', upload_to='media/uploads/', verbose_name='Image For Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model3d',
            name='imgposition',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model3d',
            name='imgrotation',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model3d',
            name='imgscale',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model3d',
            name='mouseenterscale',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
