# Generated by Django 4.1.3 on 2023-02-04 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_model3d_image_model3d_imgposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('rotation', models.CharField(max_length=100)),
                ('scale', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/uploads/', verbose_name='Image For Model')),
                ('redirecturl', models.CharField(max_length=100)),
                ('animactionsize', models.CharField(max_length=100)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant')),
            ],
        ),
    ]
