# Generated by Django 4.1.3 on 2023-02-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_mainpagemenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='mouseenterrotation',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
