# Generated by Django 4.1.3 on 2023-02-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_category_formatted_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_geo', models.CharField(max_length=100)),
                ('text_fra', models.CharField(max_length=100)),
                ('text_eng', models.CharField(max_length=100)),
                ('text_rus', models.CharField(max_length=100)),
                ('text_spa', models.CharField(max_length=100)),
                ('text_tur', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='default', upload_to='media/uploads/logos', verbose_name='Product Photo'),
            preserve_default=False,
        ),
    ]
