# Generated by Django 4.1.3 on 2023-02-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_languages_restaurant_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Text',
        ),
    ]
