# Generated by Django 4.1.3 on 2023-02-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_languages_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_geo', models.CharField(max_length=100)),
                ('text_fra', models.CharField(max_length=100)),
                ('text_eng', models.CharField(max_length=100)),
                ('text_rus', models.CharField(max_length=100)),
                ('text_spa', models.CharField(max_length=100)),
                ('text_tur', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('rotation', models.CharField(max_length=100)),
                ('font', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('visible', models.CharField(max_length=100)),
            ],
        ),
    ]
