# Generated by Django 4.1.3 on 2023-02-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_product_image3_product_image3d_product_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image3d',
            field=models.FileField(blank=True, null=True, upload_to='media/3dimages/'),
        ),
    ]
