# Generated by Django 4.1.6 on 2023-03-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_restaurant_id_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
            preserve_default=False,
        ),
    ]
