# Generated by Django 4.1.6 on 2023-03-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_category_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='media/uploads/categories', verbose_name='category Photo'),
            preserve_default=False,
        ),
    ]
